Update github-actions.yml

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -46,9 +46,10 @@ jobs:
     - name: Build with Maven
       run: mvn -B package --file talk/pom.xml
 
-  deploy:
+  docker-hub:
     runs-on: ubuntu-latest
-    name: Docker image push & ec2 deploy
+    name: Docker image push
+    needs: [ build ]
     if: github.event_name == 'push'
     steps:
     
@@ -76,40 +77,46 @@ jobs:
         cache-from: type=gha
         cache-to: type=gha,mode=max
 
-    # Deploy
-    - name: Deploy to ec2
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.HOST }}
-        username: ${{ secrets.USERNAME }}
-        port: 22
-        key: ${{ secrets.PRIVATE_KEY }}
-        script: |
-            sudo docker container prune -f
-            sudo docker pull ${{ secrets.DOCKER_REPO }}/lotalk
+  deploy:
+    runs-on: ubuntu-latest
+    name: Deploy
+    needs: [ docker-hub ]
+    steps:
+      # Deploy
+      - name: Deploy to ec2
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          port: 22
+          key: ${{ secrets.PRIVATE_KEY }}
+          script: |
+              sudo docker container prune -f
+              sudo docker pull ${{ secrets.DOCKER_REPO }}/lotalk
 
-            # Enviornment varialbes
-            echo "${{ secrets.ENVIRONMENT_VARS }}" >| .env
-            export $(grep -v '^#' .env | xargs -d '\n')
+              # Enviornment varialbes
+              echo "${{ secrets.ENVIRONMENT_VARS }}" >| .env
+              export $(grep -v '^#' .env | xargs -d '\n')
 
-            # docker-compose.yml
-            curl -L -O https://raw.githubusercontent.com/WonHyong/talk_backend/main/docker-compose.yml
+              # docker-compose.yml
+              curl -L -O https://raw.githubusercontent.com/WonHyong/talk_backend/main/docker-compose.yml
             
-            docker-compose up -d --build
-            docker image prune -f
+              docker-compose up -d --build
+              docker image prune -f
 
-            ERROR_COUNT=$(docker-compose logs | grep -c ERROR)
+              ERROR_COUNT=$(docker-compose logs | grep -c ERROR)
 
-            if [ $ERROR_COUNT -gt 0 ]; then
-              echo "Found $ERROR_COUNT error(s) in container logs."
-              exit 1
-            fi
+              if [ $ERROR_COUNT -gt 0 ]; then
+                echo "Found $ERROR_COUNT error(s) in container logs."
+                exit 1
+              fi
 
   notify:
     name: Discord Notification
     runs-on: ubuntu-latest
     needs:
       - build
+      - docker-hub
       - deploy
     if: ${{ always() }}
     steps:
